### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by Digi-Ralph** [Razmoth/PGRStudio#1]
for some reason it give me the following 
[https://i.imgur.com/Tn5yI55.png](url)

P.S.  I think the problem is that it get stuck when trying to read the assest.splitX files ...

**Comment by Razmoth** [comment]
Greetings,

Which version of the game is this from, trying to load `.assets.splitX` from `v1.19.1` seems to be working.

It's worth noting that those are standard unity files as well, so they could be loaded with the original `AssetStudio`.

**Comment by Digi-Ralph** [comment]
> Greetings,
> 
> Which version of the game is this from, trying to load `.assets.splitX` from `v1.19.1` seems to be working.
> 
> It's worth noting that those are standard unity files as well, so they could be loaded with the original `AssetStudio`.

i tired both but still keep getting the same problem when it says in console [info]read assets..
and yes it's "version_name":"1.19.1"
I'm trying to extract the sound and the textures .. managed for textures by extracting files independently but the asset.splitX files are unreadable

**Comment by Razmoth** [comment]
Greetings,

Did you try to put the game files on disk root `i.e C:\ | D:\ | etc`, it might be related to permissions.

**Comment by Razmoth** [comment]
Greetings,

did it work out eventually ?
