### ISSUE TITLE
How to get a decrypted .ab file

### ISSUE THREAD

**Issue by gtxyyl** [Razmoth/PGRStudio#10]
I want to use UnityLive2DExtractor to obtain live2d files，but when I use CNStudio, I can only obtain the unlocked files. What should I do? Please help me, thank you

**Comment by Razmoth** [comment]
Greetings,

While i haven't tested it, in theory replacing `AssetStudio.dll` with the one from `CNStudio` would be enough, just make sure to select the decryption key as well.

**Comment by gtxyyl** [comment]
Hello, thank you for your reply. I copied AssetStudio.dll to UnityLive2DExtractor, but it cannot run. I don't have the ability to modify the program. Do you have time to modify it? I think it can be released as a new program.

**Comment by Razmoth** [comment]
Greetings,

Check [this](https://github.com/Razmoth/CNUnityLive2DExtractor) out
