### ISSUE TITLE
strange file

### ISSUE THREAD

**Issue by leostudiosTM** [Razmoth/PGRStudio#11]
this is not necessarily a problem and one more doubt I have some league of legends wild rift files I know the game is from unity it saves the game content in .bytes files but

at first I thought they were encrypted but even with the keys they wouldn't open so I looked in a hex editor and it doesn't have a "UnityFS" can you tell me what kind of file it is?
[https://drive.google.com/file/d/1xsrlFNheP71QIpJxwREsCeUTmjtzHfoa/view?usp=sharing](url)

**Comment by Razmoth** [comment]
Greetings,

the file sample doesn't seem to be that of `UnityCN` format, it has `FBAU` header instead.
