### ISSUE TITLE
Cannot read files

### ISSUE THREAD

**Issue by Experientiaa** [Razmoth/PGRStudio#14]
Game : Punishing Gray Raven (CN / PC Client)

Error info 
[Info] Loading C:\programming\pgrunpack\china\Punishing Gray Raven\PGR_Data\StreamingAssets\resource\matrix\00a96ac333bbe9dd73db8e8a2a5f7c69b75b4b50
[Error] Error while reading bundle file C:\programming\pgrunpack\china\Punishing Gray Raven\PGR_Data\StreamingAssets\resource\matrix\00a96ac333bbe9dd73db8e8a2a5f7c69b75b4b50
System.Exception: Invalid Signature !!
   at AssetStudio.UnityCN..ctor(EndianBinaryReader reader) in D:\a\CNStudio\CNStudio\AssetStudio\UnityCN.cs:line 33
   at AssetStudio.BundleFile.ReadUnityCN(EndianBinaryReader reader) in D:\a\CNStudio\CNStudio\AssetStudio\BundleFile.cs:line 258
   at AssetStudio.BundleFile..ctor(FileReader reader) in D:\a\CNStudio\CNStudio\AssetStudio\BundleFile.cs:line 100
   at AssetStudio.AssetsManager.LoadBundleFile(FileReader reader, String originalPath) in D:\a\CNStudio\CNStudio\AssetStudio\AssetsManager.cs:line 248

Clues
- I've found that new decrypt HEXcode is "00DF4ED46995B1BC". So I wrote it down Keys.json like this.
    "Name": "PGR GLB/KR",
    "Key": "00DF4ED46995B1BC00DF4ED46995B1BC" (Decrypt code is 16digit but you've wrote in 32 digit. And it's seem to be repeated twice 16digit code. So I did it same)
- I'm quite certain that code is correct. Cause I've already decrypted some .awb, .usm files using that code. 
- I think PC Client is not main problem. Mobile version data occured same Invalid Signature error.

Sample file : https://drive.google.com/file/d/1JPWXOuv0swxfr6l06VZAQ3fxf0CwDHI1/view?usp=sharing

**Comment by Razmoth** [comment]
Greetings,

For the key, it would be added as `30304446344544343639393542314243`.

As for the sample file provided, it works with `PGR CN/JP/TW`.

**Comment by Experientiaa** [comment]
Oh, It really works with PGR CN/JP/TW key that you provided. How dumb am I.

By the way, I can't understand why this key works with cab assetbundle files. Other .awb, usm files are fitted in the key which I wrote in first comment. Can I ask to you why this happend?

And also I can't understand why "00DF4ED46995B1BC" is turn into "30304446344544343639393542314243". It is not seems to be a HEX->decimal conversion

**Comment by Experientiaa** [comment]
If you don't want to answer, you could close this issue.

**Comment by alt3ri** [comment]
pgr keys are still working fine tho?
