### ISSUE TITLE
input other key

### ISSUE THREAD

**Issue by 28598519a** [Razmoth/PGRStudio#5]
Hi,

I know now it use specify game version to choose which PGR key should be use, but I also want use this tool to open other UnityCN asset.

Can you make a input box, and release it, so that we can have an option to input a key to decrypt, thanks?

**Comment by Razmoth** [comment]
Greetings,

This feature was added in another tool, will send the details.

**Comment by 28598519a** [comment]
> Greetings,
> 
> This feature was added in another tool, will send the details.

Hi

I had received your mail, thanks.
