### ISSUE TITLE
Plugin or Key for H0Y0 assets?

### ISSUE THREAD

**Issue by MelancholySlime** [Razmoth/PGRStudio#6]
Hi,
Sorrry for bothering you but can update your key list or make a plugin to make it work with H0Y0 assets.
- 3/1/2023 - They update content and Lasted Ver of H0Y0Sudio i had can't read the object shader anymore :< 
Thank you. very appreciated

Btw Do we have any communication place to join ? like Discord ?

**Comment by Razmoth** [comment]
Greetings,

That is another tool, it has been updated.

There is one, but it's currently locked.

**Comment by MelancholySlime** [comment]
> Greetings,
> 
> That is another tool, it has been updated.
> 
> There is one, but it's currently locked.

Oh, can u give me the url of that tool ?
Just DM me in Discord : Victorious#9216 or though email 
Thank you so much, very appreciated.

**Comment by Rafamr14** [comment]
Hi, I'm also interested in the AssetStudio version for the hoyo games, can you also send it to me? my discord is this RafaMR14#1692
