### ISSUE TITLE
no unity file can be loaded

### ISSUE THREAD

**Issue by IceSakuraAzure** [Razmoth/PGRStudio#8]
Excuse me, I used this tool to open a special game like hk or gs,but the tool show this message'no unity file can be loaded'. I find it needs a special key,so could you tell me how to unlock?Thanks.

**Comment by Razmoth** [comment]
Greetings, 

It doesn't load games directly, you will need to find the decryption key first, add it to the keys list, then select and load.

Only then it'd be able to decrypt it.

**Comment by IceSakuraAzure** [comment]
> 

so do you know how to find the decryption key？I remember this tool can open the game folder directly about half year ago.

**Comment by Razmoth** [comment]
Greetings,

Depends on the game, easiest option is to dump it at runtime.
