### ISSUE TITLE
How to export all types of files, such as ATTS files

### ISSUE THREAD

**Issue by gtxyyl** [Razmoth/PGRStudio#9]
I want to export the skeleton file of the model, thank you

**Comment by gtxyyl** [comment]
sorry,atlts file

**Comment by gtxyyl** [comment]
Or how can I export all files？

**Comment by gtxyyl** [comment]
Sorry, I found no such file through the GUI version

**Comment by Razmoth** [comment]
Greetings,

It would depend if the game uses Unity's format or Live2D.

The asset name should be a clear indicate, very likely to be either `TextAsset` or `MonoBehaviour`

**Comment by gtxyyl** [comment]
> 问候，
> 
> 这将取决于游戏是使用 Unity 的格式还是 Live2D。
> 
> 资产名称应该是一个明确的指示，很可能是`TextAsset`或者`MonoBehaviour`

Yes, I thought it was a spin animation, so I was looking for the ATLTS file, and I found out it was a live2d animation, but using assetstudio couldn't export the moc and JSON files of live2d correctly

**Comment by gtxyyl** [comment]
> Greetings,
> 
> It would depend if the game uses Unity's format or Live2D.
> 
> The asset name should be a clear indicate, very likely to be either `TextAsset` or `MonoBehaviour`

Yes, I thought it was a spin animation, so I was looking for the ATLTS file, and I found out it was a live2d animation, but using assetstudio couldn't export the moc and JSON files of live2d correctly

**Comment by Razmoth** [comment]
Greetings,

check out [this](https://github.com/Razmoth/CNUnityLive2DExtractor).
